# Generated by Django 4.2.13 on 2024-05-18 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eMail', models.CharField(max_length=100)),
                ('useName', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=100)),
                ('buy_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
